import React, { useState } from 'react';
import { Sparkles, CheckSquare, FileCode, Copy, Check, ArrowRight } from 'lucide-react';

export default function RecommendationList({ recommendations = [] }) {
  const [copiedIndex, setCopiedIndex] = useState(null);

  const copyToClipboard = (text, idx) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idx);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const getPriorityBadge = (priority) => {
    switch (priority.toUpperCase()) {
      case 'CRITICAL':
        return 'bg-red-100 text-red-800 border-red-300';
      case 'HIGH':
        return 'bg-amber-100 text-amber-800 border-amber-300';
      case 'MEDIUM':
        return 'bg-yellow-100 text-yellow-800 border-yellow-300';
      default:
        return 'bg-blue-100 text-blue-800 border-blue-300';
    }
  };

  return (
    <div className="w-full bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-lg space-y-6">
      <div className="flex items-center justify-between pb-4 border-b border-slate-200">
        <div>
          <h3 className="text-xl font-bold text-slate-900 flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-red-600" />
            AI Strategic Recommendations & Content Ideas
          </h3>
          <p className="text-xs text-slate-500 mt-0.5 font-medium">Prioritized step-by-step action plan generated by Ollama Llama 3 Agent</p>
        </div>
        <span className="px-3 py-1 bg-red-50 border border-red-200 text-red-700 text-xs font-bold rounded-full">
          {recommendations.length} AI Fixes
        </span>
      </div>

      {recommendations.length === 0 ? (
        <div className="text-center py-12 border border-dashed border-slate-300 rounded-2xl bg-slate-50">
          <p className="text-sm font-medium text-slate-600">No specific AI recommendations available for this audit.</p>
        </div>
      ) : (
        <div className="space-y-6">
          {recommendations.map((rec, idx) => {
            const steps = Array.isArray(rec.actionable_steps) ? rec.actionable_steps : [];
            const content = rec.suggested_content || {};

            return (
              <div
                key={rec.id || idx}
                className="bg-slate-50 border border-slate-200 rounded-2xl p-5 sm:p-6 space-y-4 hover:border-red-300 transition-all shadow-sm"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div className="flex items-center gap-2">
                    <span className={`px-2.5 py-0.5 text-xs font-extrabold rounded-lg border ${getPriorityBadge(rec.priority)}`}>
                      {rec.priority}
                    </span>
                    <h4 className="text-lg font-bold text-slate-900">{rec.title}</h4>
                  </div>
                  <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">
                    {rec.category.replace('_', ' ')}
                  </span>
                </div>

                <p className="text-sm text-slate-700 leading-relaxed font-medium">{rec.explanation}</p>

                {/* Step-by-Step Action Steps */}
                {steps.length > 0 && (
                  <div className="space-y-2 pt-2">
                    <h5 className="text-xs font-bold text-slate-800 uppercase tracking-wider flex items-center gap-1.5">
                      <CheckSquare className="w-4 h-4 text-emerald-600" /> Action Steps to Implement:
                    </h5>
                    <ul className="space-y-1.5 pl-2">
                      {steps.map((step, sIdx) => (
                        <li key={sIdx} className="text-xs text-slate-700 font-medium flex items-start gap-2">
                          <ArrowRight className="w-3.5 h-3.5 text-red-600 shrink-0 mt-0.5" />
                          <span>{step}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* AI Content Suggestions */}
                {content.suggested_meta_title && (
                  <div className="p-4 bg-slate-900 rounded-2xl text-slate-100 space-y-3 mt-4 shadow-md">
                    <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                      <span className="text-xs font-bold text-red-400 flex items-center gap-1.5">
                        <FileCode className="w-4 h-4" /> AI Generated SEO Content Recommendation
                      </span>
                      <button
                        onClick={() => copyToClipboard(`Title: ${content.suggested_meta_title}\nMeta Description: ${content.suggested_meta_description}\nH1: ${content.suggested_h1}`, idx)}
                        className="flex items-center gap-1 text-[11px] font-bold text-slate-300 hover:text-white px-2.5 py-1 bg-red-600 hover:bg-red-700 rounded-md transition-colors shadow-xs cursor-pointer"
                      >
                        {copiedIndex === idx ? (
                          <>
                            <Check className="w-3.5 h-3.5 text-emerald-300" /> Copied Code
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" /> Copy Snippet
                          </>
                        )}
                      </button>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                      <div className="bg-slate-800/90 p-3 rounded-xl border border-slate-700">
                        <span className="block text-slate-400 font-semibold mb-1">Proposed Meta Title:</span>
                        <p className="font-bold text-white">{content.suggested_meta_title}</p>
                      </div>

                      <div className="bg-slate-800/90 p-3 rounded-xl border border-slate-700">
                        <span className="block text-slate-400 font-semibold mb-1">Target H1 Heading:</span>
                        <p className="font-bold text-white">{content.suggested_h1}</p>
                      </div>

                      <div className="sm:col-span-2 bg-slate-800/90 p-3 rounded-xl border border-slate-700">
                        <span className="block text-slate-400 font-semibold mb-1">Proposed Meta Description:</span>
                        <p className="text-slate-200 font-medium">{content.suggested_meta_description}</p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
